services:
    nginx:
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 8000:80
        expose:
            - 80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/usr/src/app/static
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: ./docker/backend/server-entrypoint.sh
        volumes:
            - static_volume:/usr/src/app/static
        expose:
            - 8000     
volumes:
    static_volume: {}
