services:
    nginx:
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 8000:80
        expose:
            - 80
        volumes:
            - ./infra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/static
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./infra/docker/backend/Dockerfile
        volumes:
            - static_volume:/app/static
        expose:
            - 8000     
volumes:
    static_volume: {}
