# Generated by Django 3.0.2 on 2020-02-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200201_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
