# Generated by Django 3.0.2 on 2020-02-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_jobs_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='createBy',
        ),
    ]
