# Generated by Django 3.0.2 on 2020-02-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('category', models.CharField(choices=[('Recruiter', 'Recruiter'), ('Job Applicant', 'Job Applicant')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('First_name', models.CharField(max_length=15)),
            ],
        ),
    ]
